/* eslint-disable */
// AUTO-GENERATED BY @dex/pie. DO NOT EDIT.
// Title: Dex Starter API
// Version: 1.0.0
// Generated at: 2026-09-21T19:00:00.000Z

import { createPie, type PieOptions, type PieResponse } from '@dex/pie'

export interface HealthResponse {
  status: string
  uptime?: number
}

/**
 * Navigable Route Tree Contract generated from OpenAPI.
 */
export type ApiRoutes = {
  v1: {
    health: {
      get: (options?: { headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<HealthResponse, unknown>>
    }
  }
}

/**
 * Preconfigured API client factory for this OpenAPI schema.
 */
export function createApiClient(options?: Partial<PieOptions>) {
  return createPie<ApiRoutes>({
    prefix: "/api",
    baseUrl: "",
    ...options,
  })
}
